[
    {
      "CODIGOCARROCERIA": 309,
      "CARROCERIADESCRIPCION": "MODULAR"
    },
    {
      "CODIGOCARROCERIA": 8,
      "CARROCERIADESCRIPCION": "CERRADA"
    },
    {
      "CODIGOCARROCERIA": 98,
      "CARROCERIADESCRIPCION": "EQUIPO PETROLERO"
    },
    {
      "CODIGOCARROCERIA": 11,
      "CARROCERIADESCRIPCION": "BOTELLERO"
    },
    {
      "CODIGOCARROCERIA": 21,
      "CARROCERIADESCRIPCION": "CABINADO"
    },
    {
      "CODIGOCARROCERIA": 201,
      "CARROCERIADESCRIPCION": "ARTICULADO"
    },
    {
      "CODIGOCARROCERIA": 25,
      "CARROCERIADESCRIPCION": "DOBLE CABINA"
    },
    {
      "CODIGOCARROCERIA": 312,
      "CARROCERIADESCRIPCION": "MULTIPROPOSITO"
    },
    {
      "CODIGOCARROCERIA": 12,
      "CARROCERIADESCRIPCION": "PICK UP"
    },
    {
      "CODIGOCARROCERIA": 285,
      "CARROCERIADESCRIPCION": "PLATAFORMA CON ESTACAS DESMONTABLES"
    },
    {
      "CODIGOCARROCERIA": 319,
      "CARROCERIADESCRIPCION": "CARBONERA"
    },
    {
      "CODIGOCARROCERIA": 103,
      "CARROCERIADESCRIPCION": "EQUIPO IRRIGADOR DE ASFALTO"
    },
    {
      "CODIGOCARROCERIA": 102,
      "CARROCERIADESCRIPCION": "IRRIGADOR DE AGUA"
    },
    {
      "CODIGOCARROCERIA": 295,
      "CARROCERIADESCRIPCION": "VAN"
    },
    {
      "CODIGOCARROCERIA": 527,
      "CARROCERIADESCRIPCION": "FRACTURADOR"
    },
    {
      "CODIGOCARROCERIA": 501,
      "CARROCERIADESCRIPCION": "FRAC TANK"
    },
    {
      "CODIGOCARROCERIA": 29,
      "CARROCERIADESCRIPCION": "BOMBA"
    },
    {
      "CODIGOCARROCERIA": 813,
      "CARROCERIADESCRIPCION": "PLATAFORMA"
    },
    {
      "CODIGOCARROCERIA": 484,
      "CARROCERIADESCRIPCION": "CARROTALLER"
    },
    {
      "CODIGOCARROCERIA": 512,
      "CARROCERIADESCRIPCION": "CAMPAMENTO"
    },
    {
      "CODIGOCARROCERIA": 33,
      "CARROCERIADESCRIPCION": "Panel"
    },
    {
      "CODIGOCARROCERIA": 69,
      "CARROCERIADESCRIPCION": "CAMABAJA"
    },
    {
      "CODIGOCARROCERIA": 217,
      "CARROCERIADESCRIPCION": "PLANCHON"
    },
    {
      "CODIGOCARROCERIA": 18,
      "CARROCERIADESCRIPCION": "NI�ERA"
    },
    {
      "CODIGOCARROCERIA": 16,
      "CARROCERIADESCRIPCION": "GR�A"
    },
    {
      "CODIGOCARROCERIA": 14,
      "CARROCERIADESCRIPCION": "HORMIGONERO"
    },
    {
      "CODIGOCARROCERIA": 10,
      "CARROCERIADESCRIPCION": "ESTIBAS"
    },
    {
      "CODIGOCARROCERIA": 231,
      "CARROCERIADESCRIPCION": "PORTACONTENEDORES"
    },
    {
      "CODIGOCARROCERIA": 218,
      "CARROCERIADESCRIPCION": "REPARTO"
    },
    {
      "CODIGOCARROCERIA": 6,
      "CARROCERIADESCRIPCION": "RECOLECTOR COMPACTADOR"
    },
    {
      "CODIGOCARROCERIA": 5,
      "CARROCERIADESCRIPCION": "TOLVA"
    },
    {
      "CODIGOCARROCERIA": 4,
      "CARROCERIADESCRIPCION": "VOLCO"
    },
    {
      "CODIGOCARROCERIA": 3,
      "CARROCERIADESCRIPCION": "CISTERNA O TANQUE"
    },
    {
      "CODIGOCARROCERIA": 2,
      "CARROCERIADESCRIPCION": "FURG�N"
    },
    {
      "CODIGOCARROCERIA": 1,
      "CARROCERIADESCRIPCION": "ESTACAS"
    },
    {
      "CODIGOCARROCERIA": 0,
      "CARROCERIADESCRIPCION": "S.R.S"
    }
   ]